import React from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import "../styles/global.css";

function ReportViewer({ report, onClose }) {
  
  const handleDownloadPDF = async () => {
    const element = document.querySelector(".modal-report .report-body");
    
    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false
      });
      
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      
      const imgWidth = 190;
      const pageHeight = 297;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 10;
      
      pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
      
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }
      
      pdf.save(`Medical_Report_${report.patient.replace(/\s/g, '_')}_${report.date.replace(/\s/g, '_')}.pdf`);
    } catch (error) {
      console.error("PDF generation error:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };
  
  const handleDownload = () => {
    const element = document.createElement("a");
    const fileContent = `
╔════════════════════════════════════════════════════════════╗
║              MEDICAL CONSULTATION REPORT                   ║
║              Generated by VocabOPD AI System               ║
╚════════════════════════════════════════════════════════════╝

PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name:           ${report.patient}
Age:            ${report.age || 'N/A'} years
Gender:         ${report.gender || 'N/A'}
Date:           ${report.date}
Time:           ${report.time || 'N/A'}
Language:       ${report.language || 'English'}

CONSULTATION DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Chief Complaints:
${report.symptoms || 'Not specified'}

Diagnosis:
${report.diagnosis}

PRESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.prescription || report.medicine}

MEDICAL ADVICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.advice || 'Follow prescribed medication'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.aiGenerated ? '✓ AI-Generated Report' : 'Manual Report'}
Generated on: ${new Date().toLocaleString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a computer-generated report.
For any queries, please contact the doctor.
    `;
    
    const file = new Blob([fileContent], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = `Medical_Report_${report.patient.replace(/\s/g, '_')}_${report.date.replace(/\s/g, '_')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content modal-report" onClick={(e) => e.stopPropagation()}>
        
        <div className="modal-header">
          <div>
            <h2>Medical Consultation Report</h2>
            {report.aiGenerated && (
              <span className="ai-badge-modal">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
                  <path d="M2 17l10 5 10-5"></path>
                  <path d="M2 12l10 5 10-5"></path>
                </svg>
                AI Generated
              </span>
            )}
          </div>
          <button className="close-btn" onClick={onClose}>✕</button>
        </div>

        <div className="report-body">
          
          <div className="report-section-header">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
            <h3>Patient Information</h3>
          </div>

          <div className="report-grid">
            <div className="report-section">
              <label>Patient Name:</label>
              <p>{report.patient}</p>
            </div>

            {report.age && (
              <div className="report-section">
                <label>Age:</label>
                <p>{report.age} years</p>
              </div>
            )}

            {report.gender && (
              <div className="report-section">
                <label>Gender:</label>
                <p>{report.gender}</p>
              </div>
            )}

            <div className="report-section">
              <label>Date:</label>
              <p>{report.date}</p>
            </div>

            {report.time && (
              <div className="report-section">
                <label>Time:</label>
                <p>{report.time}</p>
              </div>
            )}

            {report.language && (
              <div className="report-section">
                <label>Language:</label>
                <p>{report.language}</p>
              </div>
            )}
          </div>

          <div className="report-section-header">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
            <h3>Consultation Details</h3>
          </div>

          {report.symptoms && (
            <div className="report-section full-width">
              <label>Chief Complaints:</label>
              <p>{report.symptoms}</p>
            </div>
          )}

          <div className="report-section full-width">
            <label>Diagnosis:</label>
            <p className="diagnosis-text">{report.diagnosis}</p>
          </div>

          <div className="report-section-header">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
              <line x1="9" y1="9" x2="15" y2="9"></line>
              <line x1="9" y1="15" x2="15" y2="15"></line>
            </svg>
            <h3>Prescription</h3>
          </div>

          <div className="report-section full-width">
            <label>Prescribed Medicine:</label>
            <p className="prescription-text">{report.prescription || report.medicine}</p>
          </div>

          {report.advice && (
            <>
              <div className="report-section-header">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M12 16v-4"></path>
                  <path d="M12 8h.01"></path>
                </svg>
                <h3>Medical Advice</h3>
              </div>

              <div className="report-section full-width">
                <p className="advice-text">{report.advice}</p>
              </div>
            </>
          )}

        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={onClose}>
            Close
          </button>
          <button className="print-btn" onClick={handlePrint}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6 9 6 2 18 2 18 9"></polyline>
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
              <rect x="6" y="14" width="12" height="8"></rect>
            </svg>
            Print Report
          </button>
          <button className="download-btn" onClick={handleDownloadPDF}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <polyline points="7 10 12 15 17 10"></polyline>
              <line x1="12" y1="15" x2="12" y2="3"></line>
            </svg>
            Download PDF
          </button>
          <button className="download-btn" onClick={handleDownload}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <polyline points="7 10 12 15 17 10"></polyline>
              <line x1="12" y1="15" x2="12" y2="3"></line>
            </svg>
            Download TXT
          </button>
        </div>

      </div>
    </div>
  );
}

export default ReportViewer;
