import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import ReportViewer from "../components/ReportViewer";
import { getAllReports, createNotification } from "../services/api";
import { getProfilePicture } from "../utils/avatar";
import "../styles/global.css";
import "../styles/medical-colors.css";
import "../styles/reports-modern.css";

function Reports(){

const navigate = useNavigate();
const [selectedReport, setSelectedReport] = useState(null);
const [profilePicture, setProfilePicture] = useState(null);
const [filterStatus, setFilterStatus] = useState("all");
const [searchTerm, setSearchTerm] = useState("");
const [sortBy, setSortBy] = useState("date");
const [reports, setReports] = useState([]);
const [loading, setLoading] = useState(false);

useEffect(() => {
  const savedPicture = localStorage.getItem('profilePicture');
  const savedDoctor = localStorage.getItem('doctor');

  if (savedDoctor) {
    const doctor = JSON.parse(savedDoctor);
    const name = doctor.name || "Doctor";
    
    // Set profile picture (custom or default avatar)
    setProfilePicture(getProfilePicture(savedPicture, name));
  }

  // Load reports from backend
  loadReports();
}, []);

const loadReports = async () => {
  setLoading(true);
  try {
    // Load from backend API only - NO DUMMY DATA
    const data = await getAllReports();

    // Format the data for display
    const formattedReports = data.map(item => ({
      id: item.consultationId || item.id,
      patient: item.patient || "Unknown",
      age: item.age || "N/A",
      gender: item.gender || "N/A",
      diagnosis: item.diagnosis || "Pending Review",
      medicine: item.prescription || "As prescribed during consultation",
      prescription: item.prescription || "As prescribed during consultation",
      symptoms: item.symptoms || "N/A",
      advice: item.advice || "Follow up if symptoms persist",
      date: item.date ? new Date(item.date).toLocaleDateString() : (item.createdAt ? new Date(item.createdAt).toLocaleDateString() : "N/A"),
      time: item.time || "N/A",
      status: (item.diagnosis && item.diagnosis !== "Pending Review") ? "completed" : "pending",
      aiGenerated: !!(item.diagnosis && item.diagnosis !== "Pending Review" && item.diagnosis !== "Not provided"),
      language: item.language || "english"
    }));

    // Use only real data from database
    setReports(formattedReports);
  } catch (error) {
    console.error("Error loading reports:", error);
    // Set empty array on error - no fallback dummy data
    setReports([]);
  }
  setLoading(false);
};

const filteredReports = reports
  .filter(report => {
    if (filterStatus !== "all" && report.status !== filterStatus) return false;
    if (searchTerm && !report.patient.toLowerCase().includes(searchTerm.toLowerCase()) &&
        !report.diagnosis.toLowerCase().includes(searchTerm.toLowerCase())) return false;
    return true;
  })
  .sort((a, b) => {
    if (sortBy === "date") {
      const dateA = new Date(a.date);
      const dateB = new Date(b.date);
      return dateB - dateA;
    }
    if (sortBy === "patient") return a.patient.localeCompare(b.patient);
    return 0;
  });

const stats = {
  total: reports.length,
  completed: reports.filter(r => r.status === "completed").length,
  pending: reports.filter(r => r.status === "pending").length,
  aiGenerated: reports.filter(r => r.aiGenerated).length
};

const handleView = (report) => {
  setSelectedReport(report);
};

const handleDownload = (report) => {
  const element = document.createElement("a");
  const fileContent = `
╔════════════════════════════════════════════════════════════╗
║              MEDICAL CONSULTATION REPORT                   ║
║              Generated by VocabOPD AI System               ║
╚════════════════════════════════════════════════════════════╝

PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name:           ${report.patient}
Age:            ${report.age} years
Gender:         ${report.gender}
Date:           ${report.date}
Time:           ${report.time}
Language:       ${report.language}

CONSULTATION DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Chief Complaints:
${report.symptoms}

Diagnosis:
${report.diagnosis}

PRESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.medicine}

MEDICAL ADVICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.advice}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.aiGenerated ? '✓ AI-Generated Report' : 'Manual Report'}
Generated on: ${new Date().toLocaleString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a computer-generated report.
For any queries, please contact the doctor.
    `;
    
  const file = new Blob([fileContent], { type: "text/plain" });
  element.href = URL.createObjectURL(file);
  element.download = `Medical_Report_${report.patient.replace(/\s/g, '_')}_${report.date.replace(/\s/g, '_')}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

const handleEmail = (report) => {
  // TODO: Implement email functionality
  alert(`Email report for ${report.patient} - Feature coming soon!`);
};

const handlePrescriptionDownload = async (report) => {
  const token = localStorage.getItem("token");
  
  // Open prescription PDF in new tab
  const url = `http://localhost:5000/api/prescription/${report.id}`;
  
  fetch(url, {
    headers: {
      'Authorization': `Bearer ${token}`
    }
  })
  .then(response => {
    if (!response.ok) {
      throw new Error('Failed to generate prescription');
    }
    return response.blob();
  })
  .then(async blob => {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Prescription_${report.patient.replace(/\s/g, '_')}_${Date.now()}.pdf`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
    
    // Create notification
    await createNotification(`Prescription downloaded for ${report.patient}`);
  })
  .catch(error => {
    console.error('Prescription download error:', error);
    alert('Failed to download prescription. Please try again.');
  });
};

const handlePrint = (report) => {
  setSelectedReport(report);
  setTimeout(() => window.print(), 100);
};

const closeModal = () => {
  setSelectedReport(null);
};

return(

<>

<div className="dashboard-container">

<Sidebar/>

<div className="dashboard-main">

<Navbar profilePicture={profilePicture} pageTitle="Medical Reports" />

<div className="dashboard-content">

{/* Header Section */}
<div className="reports-header">
  <div className="reports-header-left">
    <h1>AI Medical Reports</h1>
    <p>View, download, and manage patient consultation reports</p>
  </div>
  <button className="btn-generate-report" onClick={() => navigate('/record')}>
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
      <path d="M2 17l10 5 10-5"></path>
      <path d="M2 12l10 5 10-5"></path>
    </svg>
    Generate New Report
  </button>
</div>

{/* Stats Cards */}
<div className="reports-stats">
  <div className="report-stat-card">
    <div className="stat-icon" style={{ background: '#dbeafe', color: '#2563eb' }}>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
        <polyline points="14 2 14 8 20 8"></polyline>
      </svg>
    </div>
    <div className="stat-content">
      <p>Total Reports</p>
      <h3>{stats.total}</h3>
    </div>
  </div>

  <div className="report-stat-card">
    <div className="stat-icon" style={{ background: '#d1fae5', color: '#10b981' }}>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <polyline points="20 6 9 17 4 12"></polyline>
      </svg>
    </div>
    <div className="stat-content">
      <p>Completed</p>
      <h3>{stats.completed}</h3>
    </div>
  </div>

  <div className="report-stat-card">
    <div className="stat-icon" style={{ background: '#fef3c7', color: '#f59e0b' }}>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <circle cx="12" cy="12" r="10"></circle>
        <polyline points="12 6 12 12 16 14"></polyline>
      </svg>
    </div>
    <div className="stat-content">
      <p>Pending</p>
      <h3>{stats.pending}</h3>
    </div>
  </div>

  <div className="report-stat-card">
    <div className="stat-icon" style={{ background: '#e0e7ff', color: '#6366f1' }}>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
        <path d="M2 17l10 5 10-5"></path>
        <path d="M2 12l10 5 10-5"></path>
      </svg>
    </div>
    <div className="stat-content">
      <p>AI Generated</p>
      <h3>{stats.aiGenerated}</h3>
    </div>
  </div>
</div>

{/* Filters and Search */}
<div className="reports-controls">
  <div className="search-box">
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <circle cx="11" cy="11" r="8"></circle>
      <path d="m21 21-4.35-4.35"></path>
    </svg>
    <input
      type="text"
      placeholder="Search by patient name or diagnosis..."
      value={searchTerm}
      onChange={(e) => setSearchTerm(e.target.value)}
    />
  </div>

  <div className="filter-group">
    <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
      <option value="all">All Status</option>
      <option value="completed">Completed</option>
      <option value="pending">Pending</option>
    </select>

    <select value={sortBy} onChange={(e) => setSortBy(e.target.value)}>
      <option value="date">Sort by Date</option>
      <option value="patient">Sort by Patient</option>
    </select>
  </div>
</div>

{/* Loading State */}
{loading ? (
  <div style={{ textAlign: "center", padding: "60px", color: "#6b7280" }}>
    <div style={{ fontSize: "18px", marginBottom: "10px" }}>Loading reports...</div>
    <div style={{ fontSize: "14px", color: "#9ca3af" }}>Fetching data from database</div>
  </div>
) : (
  <>
    {/* Reports Grid */}
    <div className="reports-grid">
      {filteredReports.map((report) => (
        <div key={report.id} className="report-card">
          <div className="report-card-header">
            <div className="patient-info-header">
              <div className="patient-avatar-report">
                {report.patient.charAt(0)}
              </div>
              <div>
                <h3>{report.patient}</h3>
                <p>{report.age} years • {report.gender}</p>
              </div>
            </div>
            <span className={`status-badge ${report.status}`}>
              {report.status === 'completed' ? 'Completed' : 'Pending'}
            </span>
          </div>

          <div className="report-card-body">
            <div className="report-detail">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
              <div>
                <label>Diagnosis</label>
                <p>{report.diagnosis}</p>
              </div>
            </div>

            <div className="report-detail">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                <line x1="9" y1="9" x2="15" y2="9"></line>
                <line x1="9" y1="15" x2="15" y2="15"></line>
              </svg>
              <div>
                <label>Prescription</label>
                <p>{report.medicine.length > 50 ? report.medicine.substring(0, 50) + '...' : report.medicine}</p>
              </div>
            </div>

            <div className="report-detail">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                <line x1="16" y1="2" x2="16" y2="6"></line>
                <line x1="8" y1="2" x2="8" y2="6"></line>
                <line x1="3" y1="10" x2="21" y2="10"></line>
              </svg>
              <div>
                <label>Date & Time</label>
                <p>{report.date} • {report.time}</p>
              </div>
            </div>

            {report.aiGenerated && (
              <div className="ai-badge">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
                  <path d="M2 17l10 5 10-5"></path>
                  <path d="M2 12l10 5 10-5"></path>
                </svg>
                AI Generated • {report.language}
              </div>
            )}
          </div>

          <div className="report-card-footer">
            <button className="btn-icon-action" onClick={() => handleView(report)} title="View Report">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                <circle cx="12" cy="12" r="3"></circle>
              </svg>
            </button>
            <button className="btn-icon-action" onClick={() => handlePrescriptionDownload(report)} title="Download Prescription PDF">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                <polyline points="14 2 14 8 20 8"></polyline>
                <line x1="12" y1="18" x2="12" y2="12"></line>
                <line x1="9" y1="15" x2="12" y2="18"></line>
                <line x1="15" y1="15" x2="12" y2="18"></line>
              </svg>
            </button>
            <button className="btn-icon-action" onClick={() => handleDownload(report)} title="Download">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                <polyline points="7 10 12 15 17 10"></polyline>
                <line x1="12" y1="15" x2="12" y2="3"></line>
              </svg>
            </button>
            <button className="btn-icon-action" onClick={() => handlePrint(report)} title="Print">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="6 9 6 2 18 2 18 9"></polyline>
                <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                <rect x="6" y="14" width="12" height="8"></rect>
              </svg>
            </button>
            <button className="btn-icon-action" onClick={() => handleEmail(report)} title="Email">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                <polyline points="22,6 12,13 2,6"></polyline>
              </svg>
            </button>
          </div>
        </div>
      ))}
    </div>

    {filteredReports.length === 0 && !loading && (
      <div className="empty-state">
        <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
          <polyline points="14 2 14 8 20 8"></polyline>
        </svg>
        <h3>No reports found</h3>
        <p>{searchTerm ? "Try adjusting your search or filter criteria" : "Start by recording a consultation to generate reports"}</p>
        <button className="btn-primary" onClick={() => navigate('/record')} style={{ marginTop: "20px" }}>
          Record New Consultation
        </button>
      </div>
    )}
  </>
)}

</div>

</div>

</div>

{selectedReport && (
  <ReportViewer report={selectedReport} onClose={closeModal} />
)}

</>

);

}

export default Reports;
